#ifdef BaseBuildingPlus
modded class BBP_Blueprint extends BBP_CRAFTINGBOOK_BASE{

	override void RegisterRecipies(){
		AddNewRecipe(new BBPRecipeBase("(T1-2-3) Wall Kit", "BBP_Wall_Kit", new BBPRecipePreviewItem("BBP_Bwall", {"frame","t1_door","t1_wall_planks"}, "0 180 180"), { new BBPRecipeItem("Nail", 5), new BBPRecipeItem("WoodenPlank", 5)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("(T1-2-3) Door Kit", "BBP_Door_Kit", new BBPRecipePreviewItem("BBP_BDoor", {"frame","t1_wall_planks"}, "0 180 180"), { new BBPRecipeItem("Nail", 5), new BBPRecipeItem("WoodenPlank", 5) }, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("(T1-2-3) Floor Kit", "BBP_Floor_Kit", new BBPRecipePreviewItem("BBP_Bfloor", {"frame","t1_wall_logs_horizontal"}, "-45 180 200"), { new BBPRecipeItem("Nail", 5), new BBPRecipeItem("WoodenPlank", 5)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("(T1-2-3) Roof Kit", "BBP_Roof_Kit", new BBPRecipePreviewItem("BBP_Broof", {"frame","t1_door","t1_wall_logs_horizontal"}, "-45 180 200"), { new BBPRecipeItem("Nail", 5), new BBPRecipeItem("WoodenPlank", 5)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("(T1-2-3) Gate Kit", "BBP_Gate_Kit", new BBPRecipePreviewItem("BBP_RGate", {"frame","t1_wall_logs_horizontal"}, "0 180 180"), { new BBPRecipeItem("Nail", 5), new BBPRecipeItem("WoodenPlank", 5)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("(T1-2-3) Garage Door Kit", "BBP_SGate_Kit", new BBPRecipePreviewItem("BBP_SGate", {"frame","t1_wall_logs_horizontal"}, "0 180 180"), { new BBPRecipeItem("Nail", 5), new BBPRecipeItem("WoodenPlank", 5)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("Ramp Kit", "BBP_Ramp_Kit", new BBPRecipePreviewItem("BBP_Bramp", {"frame"}, "0 45 200"), { new BBPRecipeItem("Nail", 5), new BBPRecipeItem("WoodenPlank", 5)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("Stair Kit", "BBP_Stair_Kit", new BBPRecipePreviewItem("BBP_Bstair", {"frame"}, "0 180 200"), { new BBPRecipeItem("Nail", 5), new BBPRecipeItem("WoodenPlank", 5)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("(T1-2-3) Window Kit", "BBP_Window_Kit", new BBPRecipePreviewItem("BBP_BWindow", {"frame","t1_wall_planks"}, "0 180 180"), { new BBPRecipeItem("Nail", 5), new BBPRecipeItem("WoodenPlank", 5)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("(T1-2-3) Half Wall Kit", "BBP_Half_Wall_Kit", new BBPRecipePreviewItem("BBP_Half_Bwall", {"frame","t1_wall_logs_horizontal"}, "0 180 180"), { new BBPRecipeItem("Nail", 5), new BBPRecipeItem("WoodenPlank", 5)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("Pillar Kit", "BBP_Pillar_Kit", new BBPRecipePreviewItem("BBP_Bpillar", {"frame"}, "0 0 180"), { new BBPRecipeItem("Nail", 5), new BBPRecipeItem("WoodenPlank", 5)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("(T1-2-3) Hanger Roof Kit", "BBP_Hanger_Roof_Kit", new BBPRecipePreviewItem("BBP_LHanger_Roof", {"frame","t1_wall_logs_horizontal"}, "-45 180 200"), { new BBPRecipeItem("Nail", 5), new BBPRecipeItem("WoodenPlank", 5)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("(T1-2-3) Triangle Foundation Kit", "BBP_Triangle_Foundation_Kit", new BBPRecipePreviewItem("BBP_Triangle_Foundation", {"frame","t1_wall_logs_horizontal"}, "0 180 180"), { new BBPRecipeItem("Nail", 5), new BBPRecipeItem("WoodenPlank", 5)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("(T1-2-3) Foundation Kit", "BBP_Foundation_Kit", new BBPRecipePreviewItem("BBP_BFoundation", {"frame","t1_wall_logs_horizontal"}, "0 180 180"), { new BBPRecipeItem("Nail", 5), new BBPRecipeItem("WoodenPlank", 5)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("(T1-2-3) Roof Hatch Kit", "BBP_Roof_Hatch_Kit", new BBPRecipePreviewItem("BBP_Roof_Hatch", {"frame","t1_wall_logs_horizontal", "stair"}, "25 180 200"), { new BBPRecipeItem("Nail", 5), new BBPRecipeItem("WoodenPlank", 5)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("(T1-2-3) Floor Hatch Kit", "BBP_Floor_Hatch_Kit", new BBPRecipePreviewItem("BBP_Floor_Hatch", {"frame","t1_wall_logs_horizontal", "stair"}, "25 180 200"), { new BBPRecipeItem("Nail", 5), new BBPRecipeItem("WoodenPlank", 5)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));		
		AddNewRecipe(new BBPRecipeBase("(T1-2-3) Slope Roof Kit", "BBP_Slope_Roof_Kit", new BBPRecipePreviewItem("BBP_Slope_Roof", {"frame","t1_wall_logs_horizontal"}, "0 180 180"), { new BBPRecipeItem("Nail", 5), new BBPRecipeItem("WoodenPlank", 5)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("(T1-2-3) Slope Wall Kit", "BBP_Slope_Wall_Kit", new BBPRecipePreviewItem("BBP_Left_Slope_Wall", {"frame","t1_wall_planks"}, "0 180 180"), { new BBPRecipeItem("Nail", 5), new BBPRecipeItem("WoodenPlank", 5)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("(T1-2-3) Triangle Floor Kit", "BBP_Triangle_Floor_Kit", new BBPRecipePreviewItem("BBP_Triangle_Bfloor", {"frame","t1_wall_logs_horizontal"}, "-45 180 200"), { new BBPRecipeItem("Nail", 5), new BBPRecipeItem("WoodenPlank", 5)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("(T1-2-3) Triangle Roof Kit", "BBP_Triangle_Roof_Kit", new BBPRecipePreviewItem("BBP_Triangle_Broof", {"frame","t1_wall_logs_horizontal"}, "-45 180 200"), { new BBPRecipeItem("Nail", 5), new BBPRecipeItem("WoodenPlank", 5)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("(T1) Barbwire Barrier Kit", "BBP_Barbwire_Fence_Kit", new BBPRecipePreviewItem("BBP_Barbwire_Fence", {"frame","t1_wall_logs_horizontal"}, "0 180 180"), { new BBPRecipeItem("Nail", 5), new BBPRecipeItem("WoodenPlank", 5)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("(T2) Chain Link Fence Kit", "BBP_Mesh_Fence_Kit", new BBPRecipePreviewItem("BBP_Mesh_Fence", {"frame","t2_metal","t2_metal_2"}, "0 180 180"), { new BBPRecipeItem("Nail", 5), new BBPRecipeItem("WoodenPlank", 5)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("(T2) Chain Link Gate Kit", "BBP_Mesh_Gate_Kit", new BBPRecipePreviewItem("BBP_Mesh_Gate", {"frame","t2_metal","t2_door","t2_metal_2"}, "0 180 180"), { new BBPRecipeItem("Nail", 5), new BBPRecipeItem("WoodenPlank", 5)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("(T2) Metal Floor Mesh Kit", "BBP_Floor_Mesh_Kit", new BBPRecipePreviewItem("BBP_Floor_Mesh", {"frame","t2_metal"}, "45 180 200"), { new BBPRecipeItem("Nail", 5), new BBPRecipeItem("WoodenPlank", 5)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
		AddNewRecipe(new BBPRecipeBase("(T2) Metal Stair Kit", "BBP_Metal_Stair_Kit", new BBPRecipePreviewItem("BBP_Metal_Stair", {"frame","railing_1","railing_2"}, "0 180 180"), { new BBPRecipeItem("Nail", 5), new BBPRecipeItem("WoodenPlank", 5)}, { new BBPRecipeTool("HandSaw"), new BBPRecipeTool("BBP_TapeMeasure")}));
	}

}
#endif